

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChallengeBD2.GerenciadorDeDados.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Challenge_BDEntities : DbContext
{
    public Challenge_BDEntities()
        : base("name=Challenge_BDEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Postagens> Postagens { get; set; }

    public virtual DbSet<PostagensProcessadas> PostagensProcessadas { get; set; }

}

}

