
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChallengeBD2.GerenciadorDeDados.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PostagensProcessadas
{

    public long IdPost { get; set; }

    public string PostProcessado { get; set; }



    public virtual Postagens Postagens { get; set; }

}

}
